# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w3lN5jjStdoFSbejtZ3-eayNhNBEST0y
"""

!pip install python-telegram-bot
!pip install adafruit-io
from telegram.ext import Updater,CommandHandler,MessageHandler,Filters
from Adafruit_IO import Client,Data
import os

def turnoffthelight(update, context):
  context.bot.send_message(chat_id=update.effective_chat.id, text="Bulb turned off")
  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://i.pinimg.com/originals/17/14/6e/17146e5dbf58e7b544472afc23cabced.jpg')
  send_value(0)
def turnonthelight(update, context):
  context.bot.send_message(chat_id=update.effective_chat.id, text="Bulb turned on")
  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://cdn4.vectorstock.com/i/1000x1000/48/08/realistic-glowing-light-bulb-on-dark-background-vector-3374808.jpg')
  send_value(1)

def send_value(value):
  feed = aio.feeds('bot001')
  aio.send_data(feed.key,value)

def input_message(update, context):
  text=update.message.text
  if text == 'turnonthelight':
    send_value(1)
    context.bot.send_message(chat_id=update.effective_chat.id,text="Bulb turned on")
    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://cdn4.vectorstock.com/i/1000x1000/48/08/realistic-glowing-light-bulb-on-dark-background-vector-3374808.jpg')
  elif text == 'turnoffthelight':
    send_value(0)
    context.bot.send_message(chat_id=update.effective_chat.id,text="Bulb turned off")
    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://i.pinimg.com/originals/17/14/6e/17146e5dbf58e7b544472afc23cabced.jpg')

def start(update,context):
  start_message='''
/turnoff the light or 'turn off':To turn off the bulb ,sends value=0 in feed
/turnon the light or 'turn on'  :To turn on the bulb ,sends value=1 in feed
'''
  context.bot.send_message(chat_id=update.effective_chat.id, text=start_message)

ADAFRUIT_IO_USERNAME =  os.getenv('SANJAI171')
ADAFRUIT_IO_KEY = os.getenv('aio_NDaf94ULRZPNJPYkfAPjh5GbdXzT')
TOKEN = os.getenv('1230158973:AAG3Y-UZSRghqSRiRgAaoZSmgloUikZ5LYA')

aio = Client('SANJAI171','aio_NDaf94ULRZPNJPYkfAPjh5GbdXzT')
updater=Updater('1230158973:AAG3Y-UZSRghqSRiRgAaoZSmgloUikZ5LYA',use_context=True)
dispatcher = updater.dispatcher
dispatcher.add_handler(CommandHandler('turnoffthelight',turnoffthelight))
dispatcher.add_handler(CommandHandler('turnonthelight',turnonthelight))
dispatcher.add_handler(CommandHandler('start',start))
dispatcher.add_handler(MessageHandler(Filters.text & (~Filters.command),input_message))
updater.start_polling()
updater.idle()